# Generated by Django 5.2.12 on 2026-03-16 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dispatch", "0001_initial"),
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("confirmed", "Підтверджено"),
                            ("in_progress", "Виконується"),
                            ("completed", "Виконано"),
                            ("cancelled", "Скасовано"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_auto",
                    models.BooleanField(default=False, verbose_name="Авто-маршрут"),
                ),
                (
                    "scheduled_departure",
                    models.DateTimeField(verbose_name="Запланований виїзд"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Нотатки")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_routes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_routes",
                        to="locations.location",
                        verbose_name="Куди",
                    ),
                ),
                (
                    "dispatch_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="dispatch.dispatchgroup",
                        verbose_name="Dispatch група",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Водій",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_routes",
                        to="locations.location",
                        verbose_name="Звідки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршрути",
                "ordering": ["-created_at"],
            },
        ),
    ]
