# Generated by Django 5.2.12 on 2026-03-28 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0002_alter_dispatchgroup_options_and_more"),
        ("locations", "0001_initial"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RouteStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        db_index=True, verbose_name="Порядок"
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("origin", "Стартова точка"),
                            ("transit", "Проміжна точка"),
                            ("destination", "Кінцева точка"),
                        ],
                        db_index=True,
                        default="transit",
                        max_length=20,
                        verbose_name="Тип кроку",
                    ),
                ),
                (
                    "planned_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Планове прибуття"
                    ),
                ),
                (
                    "planned_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Плановий виїзд"
                    ),
                ),
                (
                    "actual_arrival",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактичне прибуття"
                    ),
                ),
                (
                    "actual_departure",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактичний виїзд"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Нотатки")),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Створено"
                    ),
                ),
            ],
            options={
                "verbose_name": "Крок маршруту",
                "verbose_name_plural": "Кроки маршруту",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AlterModelOptions(
            name="route",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Маршрут",
                "verbose_name_plural": "Маршрути",
            },
        ),
        migrations.AlterField(
            model_name="route",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Створено",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Створив",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route_destinations",
                to="locations.location",
                verbose_name="Куди",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="dispatch_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route",
                to="dispatch.dispatchgroup",
                verbose_name="Dispatch група",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Водій",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="is_auto",
            field=models.BooleanField(
                default=False, verbose_name="Автоматично згенерований"
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route_origins",
                to="locations.location",
                verbose_name="Звідки",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Чернетка"),
                    ("confirmed", "Підтверджено"),
                    ("in_progress", "Виконується"),
                    ("completed", "Виконано"),
                    ("cancelled", "Скасовано"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["status", "created_at"], name="route_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["driver", "status"], name="route_driver_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["scheduled_departure"], name="route_scheduled_departure_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="route_origin_not_destination",
            ),
        ),
        migrations.AddField(
            model_name="routestep",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="route_steps",
                to="locations.location",
                verbose_name="Локація",
            ),
        ),
        migrations.AddField(
            model_name="routestep",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="logistics.route",
                verbose_name="Маршрут",
            ),
        ),
        migrations.AddIndex(
            model_name="routestep",
            index=models.Index(
                fields=["route", "order"], name="route_step_route_order_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routestep",
            index=models.Index(
                fields=["route", "step_type"], name="route_step_route_type_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="routestep",
            constraint=models.UniqueConstraint(
                fields=("route", "order"), name="route_step_unique_route_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="routestep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("planned_arrival__isnull", True),
                    ("planned_departure__isnull", True),
                    ("planned_departure__gte", models.F("planned_arrival")),
                    _connector="OR",
                ),
                name="route_step_planned_departure_after_arrival",
            ),
        ),
        migrations.AddConstraint(
            model_name="routestep",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("actual_arrival__isnull", True),
                    ("actual_departure__isnull", True),
                    ("actual_departure__gte", models.F("actual_arrival")),
                    _connector="OR",
                ),
                name="route_step_actual_departure_after_arrival",
            ),
        ),
    ]
