# Generated by Django 5.2.12 on 2026-03-16 02:32

import dispatch.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DispatchGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=dispatch.models.generate_group_code,
                        max_length=20,
                        unique=True,
                        verbose_name="Код групи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("forming", "Формується"),
                            ("ready", "Готово до відправки"),
                            ("in_transit", "В дорозі"),
                            ("arrived", "Прибуло"),
                            ("completed", "Завершено"),
                        ],
                        default="forming",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "departed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Час відправки"
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Час прибуття"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Створено"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Створив",
                    ),
                ),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_groups",
                        to="locations.location",
                        verbose_name="Поточна локація",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_groups",
                        to="locations.location",
                        verbose_name="Куди",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driver_groups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Водій",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_groups",
                        to="locations.location",
                        verbose_name="Звідки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dispatch група",
                "verbose_name_plural": "Dispatch групи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchGroupItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="dispatch.dispatchgroup",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_items",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Елемент Dispatch групи",
                "verbose_name_plural": "Елементи Dispatch груп",
                "unique_together": {("group", "shipment")},
            },
        ),
    ]
