# Generated by Django 6.0.1 on 2026-01-29 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
        ("shipments", "0003_alter_shipment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dispatchgroupitem",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_items",
                to="shipments.shipment",
            ),
        ),
    ]
