# Generated by Django 5.2.12 on 2026-03-28 09:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispatch", "0001_initial"),
        ("locations", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatchgroup",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Dispatch група",
                "verbose_name_plural": "Dispatch групи",
            },
        ),
        migrations.AlterModelOptions(
            name="dispatchgroupitem",
            options={
                "ordering": ["-added_at", "-id"],
                "verbose_name": "Елемент Dispatch групи",
                "verbose_name_plural": "Елементи Dispatch груп",
            },
        ),
        migrations.AlterUniqueTogether(
            name="dispatchgroupitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="dispatchgroup",
            name="created_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Створено",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchgroup",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_groups",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Створив",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchgroup",
            name="status",
            field=models.CharField(
                choices=[
                    ("forming", "Формується"),
                    ("ready", "Готово до відправки"),
                    ("in_transit", "В дорозі"),
                    ("arrived", "Прибуло"),
                    ("completed", "Завершено"),
                ],
                db_index=True,
                default="forming",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchgroupitem",
            name="added_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Додано"),
        ),
        migrations.AlterField(
            model_name="dispatchgroupitem",
            name="added_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="added_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Додав",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchgroupitem",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="dispatch.dispatchgroup",
                verbose_name="Група",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchgroupitem",
            name="shipment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispatch_items",
                to="shipments.shipment",
                verbose_name="Посилка",
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchgroup",
            index=models.Index(
                fields=["status", "created_at"], name="dispatch_status_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchgroup",
            index=models.Index(
                fields=["origin", "status"], name="dispatch_origin_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatchgroup",
            index=models.Index(
                fields=["destination", "status"], name="dispatch_dest_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="dispatch_group_origin_not_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("arrived_at__isnull", True),
                    ("departed_at__isnull", False),
                    _connector="OR",
                ),
                name="dispatch_group_arrival_requires_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchgroup",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("arrived_at__isnull", True),
                    ("arrived_at__gte", models.F("departed_at")),
                    _connector="OR",
                ),
                name="dispatch_group_arrival_not_before_departure",
            ),
        ),
        migrations.AddConstraint(
            model_name="dispatchgroupitem",
            constraint=models.UniqueConstraint(
                fields=("group", "shipment"),
                name="dispatch_group_item_unique_group_shipment",
            ),
        ),
    ]
