# Generated by Django 6.0.1 on 2026-01-29 15:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tracking_code",
                    models.CharField(editable=False, max_length=32, unique=True),
                ),
                ("sender_name", models.CharField(max_length=120)),
                ("sender_phone", models.CharField(max_length=32)),
                ("recipient_name", models.CharField(max_length=120)),
                ("recipient_phone", models.CharField(max_length=32)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("letter", "Letter"),
                            ("big_letter", "Big letter"),
                            ("s", "S"),
                            ("m", "M"),
                            ("l", "L"),
                            ("xl", "XL"),
                            ("xxl", "XXL"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("at_post_office", "At post office"),
                            ("in_transit_to_dc", "In transit to distribution center"),
                            ("at_dc", "At distribution center"),
                            ("sorted", "Sorted"),
                            ("in_transit_to_dest", "In transit to destination"),
                            (
                                "arrived_to_dest_post",
                                "Arrived to destination post office",
                            ),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="destination_shipments",
                        to="locations.location",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin_shipments",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
