# Generated by Django 5.2.12 on 2026-03-16 02:32

import django.db.models.deletion
import django.utils.timezone
import shipments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        default=shipments.models.generate_tracking_number,
                        max_length=20,
                        unique=True,
                        verbose_name="Трекінг-номер",
                    ),
                ),
                (
                    "sender_first_name",
                    models.CharField(max_length=100, verbose_name="Ім'я відправника"),
                ),
                (
                    "sender_last_name",
                    models.CharField(
                        max_length=100, verbose_name="Прізвище відправника"
                    ),
                ),
                (
                    "sender_patronymic",
                    models.CharField(
                        max_length=100, verbose_name="По-батькові відправника"
                    ),
                ),
                (
                    "sender_phone",
                    models.CharField(max_length=20, verbose_name="Телефон відправника"),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email відправника"
                    ),
                ),
                (
                    "receiver_first_name",
                    models.CharField(max_length=100, verbose_name="Ім'я отримувача"),
                ),
                (
                    "receiver_last_name",
                    models.CharField(
                        max_length=100, verbose_name="Прізвище отримувача"
                    ),
                ),
                (
                    "receiver_patronymic",
                    models.CharField(
                        max_length=100, verbose_name="По-батькові отримувача"
                    ),
                ),
                (
                    "receiver_phone",
                    models.CharField(max_length=20, verbose_name="Телефон отримувача"),
                ),
                (
                    "receiver_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email отримувача"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="Вага (кг)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Ціна доставки"
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("prepaid", "Передоплата"),
                            ("cash_on_delivery", "Оплата при отриманні"),
                        ],
                        default="prepaid",
                        max_length=20,
                        verbose_name="Тип оплати",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Прийнято"),
                            ("picked_up_by_driver", "Забрано водієм"),
                            ("in_transit", "В дорозі"),
                            ("arrived_at_facility", "Прибуло до об'єкту"),
                            ("sorted", "Відсортовано"),
                            ("out_for_delivery", "Передано для доставки"),
                            ("available_for_pickup", "Очікує отримання"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Скасовано"),
                            ("returned", "Повернуто"),
                        ],
                        default="accepted",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Створено"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Зареєстрував",
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="received_shipments",
                        to="locations.location",
                        verbose_name="Відділення призначення",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sent_shipments",
                        to="locations.location",
                        verbose_name="Відділення відправлення",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посилка",
                "verbose_name_plural": "Посилки",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сума"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Оплачено"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Час оплати"
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shipment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Оплата",
                "verbose_name_plural": "Оплати",
            },
        ),
    ]
