# Generated by Django 6.0.1 on 2026-01-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_code_location_parent_dc_alter_location_type"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="destination",
            field=models.ForeignKey(
                limit_choices_to={"type": "post_office"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="destination_shipments",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="origin",
            field=models.ForeignKey(
                limit_choices_to={"type": "post_office"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="origin_shipments",
                to="locations.location",
            ),
        ),
    ]
