# Generated by Django 5.2.12 on 2026-04-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="current_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_shipments",
                to="locations.location",
                verbose_name="Поточна локація",
            ),
        ),
        migrations.CreateModel(
            name="ShipmentRouteStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Порядок кроку")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Очікує"),
                            ("active", "Активний"),
                            ("done", "Завершений"),
                            ("skipped", "Пропущений"),
                            ("canceled", "Скасований"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус кроку",
                    ),
                ),
                (
                    "actual_arrival_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактичне прибуття"
                    ),
                ),
                (
                    "actual_departure_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Фактичне вибуття"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Створено"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Оновлено"),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipment_route_steps",
                        to="locations.location",
                        verbose_name="Локація маршруту",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_steps",
                        to="shipments.shipment",
                        verbose_name="Посилка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Крок маршруту посилки",
                "verbose_name_plural": "Кроки маршруту посилок",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("shipment", "order"),
                        name="uniq_shipment_route_step_order",
                    )
                ],
            },
        ),
    ]
