# Generated by Django 6.0.1 on 2026-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0002_alter_shipment_destination_alter_shipment_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("at_post_office", "At post office"),
                    ("in_transit_to_sorting_city", "In transit to sorting city"),
                    ("at_sorting_city", "At sorting city"),
                    ("sorted_waiting_for_dispatch", "Sorted, waiting for dispatch"),
                    (
                        "in_transit_to_distribution_center",
                        "In transit to distribution center",
                    ),
                    ("at_distribution_center", "At distribution center"),
                    (
                        "sorted_waiting_for_post_office",
                        "Sorted, waiting for post office",
                    ),
                    ("in_transit_to_post_office", "In transit to post office"),
                    ("ready_for_pickup", "Ready for pickup"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="created",
                max_length=64,
            ),
        ),
    ]
