# Generated by Django 6.0.1 on 2026-01-29 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("locations", "0003_alter_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="assigned_location",
            field=models.ForeignKey(
                blank=True,
                help_text="Для post_worker -> Post Office, для warehouse_worker -> Distribution Center",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_users",
                to="locations.location",
            ),
        ),
    ]
