# Generated by Django 6.0.1 on 2026-01-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_assigned_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("hr", "HR"),
                    ("postal_worker", "Postal worker"),
                    ("warehouse_worker", "Warehouse worker"),
                    ("logist", "Logist"),
                    ("driver", "Driver"),
                    ("admin", "Admin"),
                ],
                default="customer",
                max_length=32,
            ),
        ),
    ]
