# Generated by Django 6.0.1 on 2026-01-30 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_role"),
        ("locations", "0004_location_parent_sc_alter_location_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="assigned_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_users",
                to="locations.location",
            ),
        ),
    ]
