# Generated by Django 5.2.12 on 2026-03-16 02:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        ("shipments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("accepted", "Прийнято"),
                            ("picked_up_by_driver", "Забрано водієм"),
                            ("in_transit", "В дорозі"),
                            ("arrived_at_facility", "Прибуло до об'єкту"),
                            ("sorted", "Відсортовано"),
                            ("out_for_delivery", "Передано для доставки"),
                            ("available_for_pickup", "Очікує отримання"),
                            ("delivered", "Доставлено"),
                            ("cancelled", "Скасовано"),
                            ("returned", "Повернуто"),
                            ("note", "Нотатка"),
                        ],
                        max_length=30,
                        verbose_name="Тип події",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Нотатка")),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Публічна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Час події"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="locations.location",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="shipments.shipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подія відстеження",
                "verbose_name_plural": "Події відстеження",
                "ordering": ["-created_at"],
            },
        ),
    ]
