# Generated by Django 6.0.1 on 2026-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("post_office", "Post office"),
                            ("distribution_center", "Distribution center"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("address", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
