# Generated by Django 5.2.12 on 2026-03-16 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Назва міста")),
            ],
            options={
                "verbose_name": "Місто",
                "verbose_name_plural": "Міста",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Назва регіону"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=10, unique=True, verbose_name="Код регіону"
                    ),
                ),
            ],
            options={
                "verbose_name": "Регіон",
                "verbose_name_plural": "Регіони",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("post_office", "Поштове відділення"),
                            ("sorting_center", "Сортувальний центр"),
                            ("distribution_center", "Розподільчий центр"),
                        ],
                        max_length=30,
                        verbose_name="Тип",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адреса")),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Код"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активне"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="locations.city",
                        verbose_name="Місто",
                    ),
                ),
                (
                    "parent_dc",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "distribution_center"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="post_offices",
                        to="locations.location",
                        verbose_name="Батьківський розподільчий центр",
                    ),
                ),
                (
                    "parent_sc",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"type": "sorting_center"},
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="distribution_centers",
                        to="locations.location",
                        verbose_name="Батьківський сортувальний центр",
                    ),
                ),
            ],
            options={
                "verbose_name": "Локація",
                "verbose_name_plural": "Локації",
                "ordering": ["code", "name"],
            },
        ),
        migrations.AddField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cities",
                to="locations.region",
                verbose_name="Регіон",
            ),
        ),
    ]
