# Generated by Django 6.0.1 on 2026-01-29 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=5, unique=True
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="parent_dc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "distribution_center"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_offices",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("distribution_center", "Distribution center"),
                    ("post_office", "Post office"),
                ],
                max_length=32,
            ),
        ),
    ]
