# Generated by Django 6.0.1 on 2026-01-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0002_location_code_location_parent_dc_alter_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
