# Generated by Django 6.0.1 on 2026-01-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0003_alter_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="parent_sc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "sorting_city"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="post_offices",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=9, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="parent_dc",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"type": "distribution_center"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sorting_cities",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("distribution_center", "Distribution center"),
                    ("sorting_city", "Sorting city"),
                    ("post_office", "Post office"),
                ],
                max_length=32,
            ),
        ),
    ]
